apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proyecto-mlops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lccruzr/proyecto-mlops.git
    targetRevision: HEAD
    path: apps/umbrella
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
