apiVersion: v2
name: proyecto-mlops
description: Umbrella chart for the MLOps stack
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  # Off‑the‑shelf charts
  - name: airflow
    version: 1.10.0
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: mlflow
    version: 0.8.0
    repository: "oci://ghcr.io/community-charts"
  - name: minio
    version: 8.0.13
    repository: "https://charts.min.io/"
  - name: postgresql
    alias: postgres-metadata
    version: 15.5.0
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: postgresql
    alias: postgres-raw
    version: 15.5.0
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: prometheus
    version: 25.1.0
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: grafana
    version: 7.3.0
    repository: "oci://registry-1.docker.io/bitnamicharts"

  # Custom micro‑services
  - name: api
    version: 0.1.0
    repository: "file://charts/api"
  - name: ui
    version: 0.1.0
    repository: "file://charts/ui"
