# Global tag injected by CI bump-manifest job
global:
  sha: "latest"

imagePullSecrets:
  - name: dockerhub

airflow:
  executor: "LocalExecutor"
  dags:
    gitSync:
      enabled: true
      repo: https://github.com/lccruzr/proyecto-mlops
      branch: master
      depth: 1

mlflow:
  image:
    repository: lccruzr9606/mlflow-server
    tag: "{{ .Values.global.sha }}"

api:
  image:
    repository: lccruzr9606/realtor-api
    tag: "{{ .Values.global.sha }}"
  env:
    - name: MLFLOW_TRACKING_URI
      value: http://mlflow:5000

ui:
  image:
    repository: lccruzr9606/realtor-streamlit
    tag: "{{ .Values.global.sha }}"
  env:
    - name: API_URL
      value: http://api:8000

minio:
  buckets:
    - name: mlflow-artifacts
      policy: none

postgres-metadata:
  auth:
    postgresqlPassword: mlops
  primary:
    persistence:
      enabled: true
      size: 5Gi

postgres-raw:
  auth:
    postgresqlPassword: mlops
  primary:
    persistence:
      enabled: true
      size: 5Gi

prometheus: {}
grafana: {}