apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ui.fullname" . }}
  labels: {{- include "ui.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "ui.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8501
              name: http
          env:
            {{- toYaml .Values.env | nindent 20 }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
